// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: protos/fraud_detection.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Transaction Request
type TransactionRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TransactionId      string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	UserId             string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount             float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Timestamp          int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	MerchantId         string                 `protobuf:"bytes,5,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	MerchantRisk       float64                `protobuf:"fixed64,6,opt,name=merchant_risk,json=merchantRisk,proto3" json:"merchant_risk,omitempty"`
	LocationLat        float64                `protobuf:"fixed64,7,opt,name=location_lat,json=locationLat,proto3" json:"location_lat,omitempty"`
	LocationLon        float64                `protobuf:"fixed64,8,opt,name=location_lon,json=locationLon,proto3" json:"location_lon,omitempty"`
	DeviceId           string                 `protobuf:"bytes,9,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	IpAddress          string                 `protobuf:"bytes,10,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	AdditionalFeatures map[string]float64     `protobuf:"bytes,11,rep,name=additional_features,json=additionalFeatures,proto3" json:"additional_features,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TransactionRequest) Reset() {
	*x = TransactionRequest{}
	mi := &file_protos_fraud_detection_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionRequest) ProtoMessage() {}

func (x *TransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_fraud_detection_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionRequest.ProtoReflect.Descriptor instead.
func (*TransactionRequest) Descriptor() ([]byte, []int) {
	return file_protos_fraud_detection_proto_rawDescGZIP(), []int{0}
}

func (x *TransactionRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *TransactionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TransactionRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TransactionRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *TransactionRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *TransactionRequest) GetMerchantRisk() float64 {
	if x != nil {
		return x.MerchantRisk
	}
	return 0
}

func (x *TransactionRequest) GetLocationLat() float64 {
	if x != nil {
		return x.LocationLat
	}
	return 0
}

func (x *TransactionRequest) GetLocationLon() float64 {
	if x != nil {
		return x.LocationLon
	}
	return 0
}

func (x *TransactionRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *TransactionRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *TransactionRequest) GetAdditionalFeatures() map[string]float64 {
	if x != nil {
		return x.AdditionalFeatures
	}
	return nil
}

// Fraud Response
type FraudResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TransactionId    string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	IsFraud          bool                   `protobuf:"varint,2,opt,name=is_fraud,json=isFraud,proto3" json:"is_fraud,omitempty"`
	FraudScore       float64                `protobuf:"fixed64,3,opt,name=fraud_score,json=fraudScore,proto3" json:"fraud_score,omitempty"`
	Confidence       float64                `protobuf:"fixed64,4,opt,name=confidence,proto3" json:"confidence,omitempty"`
	RiskFactors      []string               `protobuf:"bytes,5,rep,name=risk_factors,json=riskFactors,proto3" json:"risk_factors,omitempty"`
	ModelVersion     string                 `protobuf:"bytes,6,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"`
	ProcessingTimeMs int64                  `protobuf:"varint,7,opt,name=processing_time_ms,json=processingTimeMs,proto3" json:"processing_time_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *FraudResponse) Reset() {
	*x = FraudResponse{}
	mi := &file_protos_fraud_detection_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FraudResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FraudResponse) ProtoMessage() {}

func (x *FraudResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_fraud_detection_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FraudResponse.ProtoReflect.Descriptor instead.
func (*FraudResponse) Descriptor() ([]byte, []int) {
	return file_protos_fraud_detection_proto_rawDescGZIP(), []int{1}
}

func (x *FraudResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *FraudResponse) GetIsFraud() bool {
	if x != nil {
		return x.IsFraud
	}
	return false
}

func (x *FraudResponse) GetFraudScore() float64 {
	if x != nil {
		return x.FraudScore
	}
	return 0
}

func (x *FraudResponse) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *FraudResponse) GetRiskFactors() []string {
	if x != nil {
		return x.RiskFactors
	}
	return nil
}

func (x *FraudResponse) GetModelVersion() string {
	if x != nil {
		return x.ModelVersion
	}
	return ""
}

func (x *FraudResponse) GetProcessingTimeMs() int64 {
	if x != nil {
		return x.ProcessingTimeMs
	}
	return 0
}

// Fraud Score Response
type FraudScoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FraudScore    float64                `protobuf:"fixed64,1,opt,name=fraud_score,json=fraudScore,proto3" json:"fraud_score,omitempty"`
	Confidence    float64                `protobuf:"fixed64,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	RiskFactors   []string               `protobuf:"bytes,3,rep,name=risk_factors,json=riskFactors,proto3" json:"risk_factors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FraudScoreResponse) Reset() {
	*x = FraudScoreResponse{}
	mi := &file_protos_fraud_detection_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FraudScoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FraudScoreResponse) ProtoMessage() {}

func (x *FraudScoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_fraud_detection_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FraudScoreResponse.ProtoReflect.Descriptor instead.
func (*FraudScoreResponse) Descriptor() ([]byte, []int) {
	return file_protos_fraud_detection_proto_rawDescGZIP(), []int{2}
}

func (x *FraudScoreResponse) GetFraudScore() float64 {
	if x != nil {
		return x.FraudScore
	}
	return 0
}

func (x *FraudScoreResponse) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *FraudScoreResponse) GetRiskFactors() []string {
	if x != nil {
		return x.RiskFactors
	}
	return nil
}

// Fraud Alert
type FraudAlert struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AlertId         string                 `protobuf:"bytes,1,opt,name=alert_id,json=alertId,proto3" json:"alert_id,omitempty"`
	TransactionId   string                 `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	AlertType       string                 `protobuf:"bytes,3,opt,name=alert_type,json=alertType,proto3" json:"alert_type,omitempty"`
	Severity        string                 `protobuf:"bytes,4,opt,name=severity,proto3" json:"severity,omitempty"`
	Description     string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	ConfidenceScore float64                `protobuf:"fixed64,6,opt,name=confidence_score,json=confidenceScore,proto3" json:"confidence_score,omitempty"`
	Timestamp       int64                  `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FraudAlert) Reset() {
	*x = FraudAlert{}
	mi := &file_protos_fraud_detection_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FraudAlert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FraudAlert) ProtoMessage() {}

func (x *FraudAlert) ProtoReflect() protoreflect.Message {
	mi := &file_protos_fraud_detection_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FraudAlert.ProtoReflect.Descriptor instead.
func (*FraudAlert) Descriptor() ([]byte, []int) {
	return file_protos_fraud_detection_proto_rawDescGZIP(), []int{3}
}

func (x *FraudAlert) GetAlertId() string {
	if x != nil {
		return x.AlertId
	}
	return ""
}

func (x *FraudAlert) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *FraudAlert) GetAlertType() string {
	if x != nil {
		return x.AlertType
	}
	return ""
}

func (x *FraudAlert) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *FraudAlert) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *FraudAlert) GetConfidenceScore() float64 {
	if x != nil {
		return x.ConfidenceScore
	}
	return 0
}

func (x *FraudAlert) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// Batch Transaction Request
type BatchTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*TransactionRequest  `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchTransactionRequest) Reset() {
	*x = BatchTransactionRequest{}
	mi := &file_protos_fraud_detection_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchTransactionRequest) ProtoMessage() {}

func (x *BatchTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_fraud_detection_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchTransactionRequest.ProtoReflect.Descriptor instead.
func (*BatchTransactionRequest) Descriptor() ([]byte, []int) {
	return file_protos_fraud_detection_proto_rawDescGZIP(), []int{4}
}

func (x *BatchTransactionRequest) GetTransactions() []*TransactionRequest {
	if x != nil {
		return x.Transactions
	}
	return nil
}

// Batch Fraud Response
type BatchFraudResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Responses             []*FraudResponse       `protobuf:"bytes,1,rep,name=responses,proto3" json:"responses,omitempty"`
	TotalProcessingTimeMs int64                  `protobuf:"varint,2,opt,name=total_processing_time_ms,json=totalProcessingTimeMs,proto3" json:"total_processing_time_ms,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *BatchFraudResponse) Reset() {
	*x = BatchFraudResponse{}
	mi := &file_protos_fraud_detection_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchFraudResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchFraudResponse) ProtoMessage() {}

func (x *BatchFraudResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_fraud_detection_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchFraudResponse.ProtoReflect.Descriptor instead.
func (*BatchFraudResponse) Descriptor() ([]byte, []int) {
	return file_protos_fraud_detection_proto_rawDescGZIP(), []int{5}
}

func (x *BatchFraudResponse) GetResponses() []*FraudResponse {
	if x != nil {
		return x.Responses
	}
	return nil
}

func (x *BatchFraudResponse) GetTotalProcessingTimeMs() int64 {
	if x != nil {
		return x.TotalProcessingTimeMs
	}
	return 0
}

// Fraud Alert Request
type FraudAlertRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SinceTimestamp int64                  `protobuf:"varint,2,opt,name=since_timestamp,json=sinceTimestamp,proto3" json:"since_timestamp,omitempty"`
	MaxAlerts      int32                  `protobuf:"varint,3,opt,name=max_alerts,json=maxAlerts,proto3" json:"max_alerts,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FraudAlertRequest) Reset() {
	*x = FraudAlertRequest{}
	mi := &file_protos_fraud_detection_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FraudAlertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FraudAlertRequest) ProtoMessage() {}

func (x *FraudAlertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_fraud_detection_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FraudAlertRequest.ProtoReflect.Descriptor instead.
func (*FraudAlertRequest) Descriptor() ([]byte, []int) {
	return file_protos_fraud_detection_proto_rawDescGZIP(), []int{6}
}

func (x *FraudAlertRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *FraudAlertRequest) GetSinceTimestamp() int64 {
	if x != nil {
		return x.SinceTimestamp
	}
	return 0
}

func (x *FraudAlertRequest) GetMaxAlerts() int32 {
	if x != nil {
		return x.MaxAlerts
	}
	return 0
}

// Model Info Request
type ModelInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelName     string                 `protobuf:"bytes,1,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelInfoRequest) Reset() {
	*x = ModelInfoRequest{}
	mi := &file_protos_fraud_detection_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelInfoRequest) ProtoMessage() {}

func (x *ModelInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_fraud_detection_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelInfoRequest.ProtoReflect.Descriptor instead.
func (*ModelInfoRequest) Descriptor() ([]byte, []int) {
	return file_protos_fraud_detection_proto_rawDescGZIP(), []int{7}
}

func (x *ModelInfoRequest) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *ModelInfoRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// Model Info
type ModelInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelName     string                 `protobuf:"bytes,1,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Accuracy      float64                `protobuf:"fixed64,3,opt,name=accuracy,proto3" json:"accuracy,omitempty"`
	Precision     float64                `protobuf:"fixed64,4,opt,name=precision,proto3" json:"precision,omitempty"`
	Recall        float64                `protobuf:"fixed64,5,opt,name=recall,proto3" json:"recall,omitempty"`
	F1Score       float64                `protobuf:"fixed64,6,opt,name=f1_score,json=f1Score,proto3" json:"f1_score,omitempty"`
	Features      []string               `protobuf:"bytes,7,rep,name=features,proto3" json:"features,omitempty"`
	TrainingDate  string                 `protobuf:"bytes,8,opt,name=training_date,json=trainingDate,proto3" json:"training_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelInfo) Reset() {
	*x = ModelInfo{}
	mi := &file_protos_fraud_detection_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelInfo) ProtoMessage() {}

func (x *ModelInfo) ProtoReflect() protoreflect.Message {
	mi := &file_protos_fraud_detection_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelInfo.ProtoReflect.Descriptor instead.
func (*ModelInfo) Descriptor() ([]byte, []int) {
	return file_protos_fraud_detection_proto_rawDescGZIP(), []int{8}
}

func (x *ModelInfo) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *ModelInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ModelInfo) GetAccuracy() float64 {
	if x != nil {
		return x.Accuracy
	}
	return 0
}

func (x *ModelInfo) GetPrecision() float64 {
	if x != nil {
		return x.Precision
	}
	return 0
}

func (x *ModelInfo) GetRecall() float64 {
	if x != nil {
		return x.Recall
	}
	return 0
}

func (x *ModelInfo) GetF1Score() float64 {
	if x != nil {
		return x.F1Score
	}
	return 0
}

func (x *ModelInfo) GetFeatures() []string {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *ModelInfo) GetTrainingDate() string {
	if x != nil {
		return x.TrainingDate
	}
	return ""
}

// Model Update Request
type ModelUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelName     string                 `protobuf:"bytes,1,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	ModelData     []byte                 `protobuf:"bytes,3,opt,name=model_data,json=modelData,proto3" json:"model_data,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelUpdateRequest) Reset() {
	*x = ModelUpdateRequest{}
	mi := &file_protos_fraud_detection_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelUpdateRequest) ProtoMessage() {}

func (x *ModelUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_fraud_detection_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelUpdateRequest.ProtoReflect.Descriptor instead.
func (*ModelUpdateRequest) Descriptor() ([]byte, []int) {
	return file_protos_fraud_detection_proto_rawDescGZIP(), []int{9}
}

func (x *ModelUpdateRequest) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *ModelUpdateRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ModelUpdateRequest) GetModelData() []byte {
	if x != nil {
		return x.ModelData
	}
	return nil
}

func (x *ModelUpdateRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Model Update Response
type ModelUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	NewVersion    string                 `protobuf:"bytes,3,opt,name=new_version,json=newVersion,proto3" json:"new_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelUpdateResponse) Reset() {
	*x = ModelUpdateResponse{}
	mi := &file_protos_fraud_detection_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelUpdateResponse) ProtoMessage() {}

func (x *ModelUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_fraud_detection_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelUpdateResponse.ProtoReflect.Descriptor instead.
func (*ModelUpdateResponse) Descriptor() ([]byte, []int) {
	return file_protos_fraud_detection_proto_rawDescGZIP(), []int{10}
}

func (x *ModelUpdateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ModelUpdateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ModelUpdateResponse) GetNewVersion() string {
	if x != nil {
		return x.NewVersion
	}
	return ""
}

// Metrics Request
type MetricsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ModelName      string                 `protobuf:"bytes,1,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	Version        string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	SinceTimestamp int64                  `protobuf:"varint,3,opt,name=since_timestamp,json=sinceTimestamp,proto3" json:"since_timestamp,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MetricsRequest) Reset() {
	*x = MetricsRequest{}
	mi := &file_protos_fraud_detection_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsRequest) ProtoMessage() {}

func (x *MetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_fraud_detection_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsRequest.ProtoReflect.Descriptor instead.
func (*MetricsRequest) Descriptor() ([]byte, []int) {
	return file_protos_fraud_detection_proto_rawDescGZIP(), []int{11}
}

func (x *MetricsRequest) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *MetricsRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *MetricsRequest) GetSinceTimestamp() int64 {
	if x != nil {
		return x.SinceTimestamp
	}
	return 0
}

// Model Metrics
type ModelMetrics struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Accuracy         float64                `protobuf:"fixed64,1,opt,name=accuracy,proto3" json:"accuracy,omitempty"`
	Precision        float64                `protobuf:"fixed64,2,opt,name=precision,proto3" json:"precision,omitempty"`
	Recall           float64                `protobuf:"fixed64,3,opt,name=recall,proto3" json:"recall,omitempty"`
	F1Score          float64                `protobuf:"fixed64,4,opt,name=f1_score,json=f1Score,proto3" json:"f1_score,omitempty"`
	TotalPredictions int64                  `protobuf:"varint,5,opt,name=total_predictions,json=totalPredictions,proto3" json:"total_predictions,omitempty"`
	TruePositives    int64                  `protobuf:"varint,6,opt,name=true_positives,json=truePositives,proto3" json:"true_positives,omitempty"`
	FalsePositives   int64                  `protobuf:"varint,7,opt,name=false_positives,json=falsePositives,proto3" json:"false_positives,omitempty"`
	TrueNegatives    int64                  `protobuf:"varint,8,opt,name=true_negatives,json=trueNegatives,proto3" json:"true_negatives,omitempty"`
	FalseNegatives   int64                  `protobuf:"varint,9,opt,name=false_negatives,json=falseNegatives,proto3" json:"false_negatives,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ModelMetrics) Reset() {
	*x = ModelMetrics{}
	mi := &file_protos_fraud_detection_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelMetrics) ProtoMessage() {}

func (x *ModelMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_protos_fraud_detection_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelMetrics.ProtoReflect.Descriptor instead.
func (*ModelMetrics) Descriptor() ([]byte, []int) {
	return file_protos_fraud_detection_proto_rawDescGZIP(), []int{12}
}

func (x *ModelMetrics) GetAccuracy() float64 {
	if x != nil {
		return x.Accuracy
	}
	return 0
}

func (x *ModelMetrics) GetPrecision() float64 {
	if x != nil {
		return x.Precision
	}
	return 0
}

func (x *ModelMetrics) GetRecall() float64 {
	if x != nil {
		return x.Recall
	}
	return 0
}

func (x *ModelMetrics) GetF1Score() float64 {
	if x != nil {
		return x.F1Score
	}
	return 0
}

func (x *ModelMetrics) GetTotalPredictions() int64 {
	if x != nil {
		return x.TotalPredictions
	}
	return 0
}

func (x *ModelMetrics) GetTruePositives() int64 {
	if x != nil {
		return x.TruePositives
	}
	return 0
}

func (x *ModelMetrics) GetFalsePositives() int64 {
	if x != nil {
		return x.FalsePositives
	}
	return 0
}

func (x *ModelMetrics) GetTrueNegatives() int64 {
	if x != nil {
		return x.TrueNegatives
	}
	return 0
}

func (x *ModelMetrics) GetFalseNegatives() int64 {
	if x != nil {
		return x.FalseNegatives
	}
	return 0
}

var File_protos_fraud_detection_proto protoreflect.FileDescriptor

const file_protos_fraud_detection_proto_rawDesc = "" +
	"\n" +
	"\x1cprotos/fraud_detection.proto\x12\x0ffraud_detection\"\x87\x04\n" +
	"\x12TransactionRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12\x1f\n" +
	"\vmerchant_id\x18\x05 \x01(\tR\n" +
	"merchantId\x12#\n" +
	"\rmerchant_risk\x18\x06 \x01(\x01R\fmerchantRisk\x12!\n" +
	"\flocation_lat\x18\a \x01(\x01R\vlocationLat\x12!\n" +
	"\flocation_lon\x18\b \x01(\x01R\vlocationLon\x12\x1b\n" +
	"\tdevice_id\x18\t \x01(\tR\bdeviceId\x12\x1d\n" +
	"\n" +
	"ip_address\x18\n" +
	" \x01(\tR\tipAddress\x12l\n" +
	"\x13additional_features\x18\v \x03(\v2;.fraud_detection.TransactionRequest.AdditionalFeaturesEntryR\x12additionalFeatures\x1aE\n" +
	"\x17AdditionalFeaturesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"\x88\x02\n" +
	"\rFraudResponse\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x19\n" +
	"\bis_fraud\x18\x02 \x01(\bR\aisFraud\x12\x1f\n" +
	"\vfraud_score\x18\x03 \x01(\x01R\n" +
	"fraudScore\x12\x1e\n" +
	"\n" +
	"confidence\x18\x04 \x01(\x01R\n" +
	"confidence\x12!\n" +
	"\frisk_factors\x18\x05 \x03(\tR\vriskFactors\x12#\n" +
	"\rmodel_version\x18\x06 \x01(\tR\fmodelVersion\x12,\n" +
	"\x12processing_time_ms\x18\a \x01(\x03R\x10processingTimeMs\"x\n" +
	"\x12FraudScoreResponse\x12\x1f\n" +
	"\vfraud_score\x18\x01 \x01(\x01R\n" +
	"fraudScore\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x01R\n" +
	"confidence\x12!\n" +
	"\frisk_factors\x18\x03 \x03(\tR\vriskFactors\"\xf4\x01\n" +
	"\n" +
	"FraudAlert\x12\x19\n" +
	"\balert_id\x18\x01 \x01(\tR\aalertId\x12%\n" +
	"\x0etransaction_id\x18\x02 \x01(\tR\rtransactionId\x12\x1d\n" +
	"\n" +
	"alert_type\x18\x03 \x01(\tR\talertType\x12\x1a\n" +
	"\bseverity\x18\x04 \x01(\tR\bseverity\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12)\n" +
	"\x10confidence_score\x18\x06 \x01(\x01R\x0fconfidenceScore\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\x03R\ttimestamp\"b\n" +
	"\x17BatchTransactionRequest\x12G\n" +
	"\ftransactions\x18\x01 \x03(\v2#.fraud_detection.TransactionRequestR\ftransactions\"\x8b\x01\n" +
	"\x12BatchFraudResponse\x12<\n" +
	"\tresponses\x18\x01 \x03(\v2\x1e.fraud_detection.FraudResponseR\tresponses\x127\n" +
	"\x18total_processing_time_ms\x18\x02 \x01(\x03R\x15totalProcessingTimeMs\"t\n" +
	"\x11FraudAlertRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12'\n" +
	"\x0fsince_timestamp\x18\x02 \x01(\x03R\x0esinceTimestamp\x12\x1d\n" +
	"\n" +
	"max_alerts\x18\x03 \x01(\x05R\tmaxAlerts\"K\n" +
	"\x10ModelInfoRequest\x12\x1d\n" +
	"\n" +
	"model_name\x18\x01 \x01(\tR\tmodelName\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"\xf2\x01\n" +
	"\tModelInfo\x12\x1d\n" +
	"\n" +
	"model_name\x18\x01 \x01(\tR\tmodelName\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1a\n" +
	"\baccuracy\x18\x03 \x01(\x01R\baccuracy\x12\x1c\n" +
	"\tprecision\x18\x04 \x01(\x01R\tprecision\x12\x16\n" +
	"\x06recall\x18\x05 \x01(\x01R\x06recall\x12\x19\n" +
	"\bf1_score\x18\x06 \x01(\x01R\af1Score\x12\x1a\n" +
	"\bfeatures\x18\a \x03(\tR\bfeatures\x12#\n" +
	"\rtraining_date\x18\b \x01(\tR\ftrainingDate\"\xf8\x01\n" +
	"\x12ModelUpdateRequest\x12\x1d\n" +
	"\n" +
	"model_name\x18\x01 \x01(\tR\tmodelName\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1d\n" +
	"\n" +
	"model_data\x18\x03 \x01(\fR\tmodelData\x12M\n" +
	"\bmetadata\x18\x04 \x03(\v21.fraud_detection.ModelUpdateRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"j\n" +
	"\x13ModelUpdateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\vnew_version\x18\x03 \x01(\tR\n" +
	"newVersion\"r\n" +
	"\x0eMetricsRequest\x12\x1d\n" +
	"\n" +
	"model_name\x18\x01 \x01(\tR\tmodelName\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12'\n" +
	"\x0fsince_timestamp\x18\x03 \x01(\x03R\x0esinceTimestamp\"\xc8\x02\n" +
	"\fModelMetrics\x12\x1a\n" +
	"\baccuracy\x18\x01 \x01(\x01R\baccuracy\x12\x1c\n" +
	"\tprecision\x18\x02 \x01(\x01R\tprecision\x12\x16\n" +
	"\x06recall\x18\x03 \x01(\x01R\x06recall\x12\x19\n" +
	"\bf1_score\x18\x04 \x01(\x01R\af1Score\x12+\n" +
	"\x11total_predictions\x18\x05 \x01(\x03R\x10totalPredictions\x12%\n" +
	"\x0etrue_positives\x18\x06 \x01(\x03R\rtruePositives\x12'\n" +
	"\x0ffalse_positives\x18\a \x01(\x03R\x0efalsePositives\x12%\n" +
	"\x0etrue_negatives\x18\b \x01(\x03R\rtrueNegatives\x12'\n" +
	"\x0ffalse_negatives\x18\t \x01(\x03R\x0efalseNegatives2\x90\x03\n" +
	"\x15FraudDetectionService\x12Y\n" +
	"\x12ProcessTransaction\x12#.fraud_detection.TransactionRequest\x1a\x1e.fraud_detection.FraudResponse\x12Y\n" +
	"\rGetFraudScore\x12#.fraud_detection.TransactionRequest\x1a#.fraud_detection.FraudScoreResponse\x12V\n" +
	"\x11StreamFraudAlerts\x12\".fraud_detection.FraudAlertRequest\x1a\x1b.fraud_detection.FraudAlert0\x01\x12i\n" +
	"\x18BatchProcessTransactions\x12(.fraud_detection.BatchTransactionRequest\x1a#.fraud_detection.BatchFraudResponse2\x8a\x02\n" +
	"\fModelService\x12M\n" +
	"\fGetModelInfo\x12!.fraud_detection.ModelInfoRequest\x1a\x1a.fraud_detection.ModelInfo\x12X\n" +
	"\vUpdateModel\x12#.fraud_detection.ModelUpdateRequest\x1a$.fraud_detection.ModelUpdateResponse\x12Q\n" +
	"\x0fGetModelMetrics\x12\x1f.fraud_detection.MetricsRequest\x1a\x1d.fraud_detection.ModelMetricsB)Z'example.com/fraud/go_api/internal/pb;pbb\x06proto3"

var (
	file_protos_fraud_detection_proto_rawDescOnce sync.Once
	file_protos_fraud_detection_proto_rawDescData []byte
)

func file_protos_fraud_detection_proto_rawDescGZIP() []byte {
	file_protos_fraud_detection_proto_rawDescOnce.Do(func() {
		file_protos_fraud_detection_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_fraud_detection_proto_rawDesc), len(file_protos_fraud_detection_proto_rawDesc)))
	})
	return file_protos_fraud_detection_proto_rawDescData
}

var file_protos_fraud_detection_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_protos_fraud_detection_proto_goTypes = []any{
	(*TransactionRequest)(nil),      // 0: fraud_detection.TransactionRequest
	(*FraudResponse)(nil),           // 1: fraud_detection.FraudResponse
	(*FraudScoreResponse)(nil),      // 2: fraud_detection.FraudScoreResponse
	(*FraudAlert)(nil),              // 3: fraud_detection.FraudAlert
	(*BatchTransactionRequest)(nil), // 4: fraud_detection.BatchTransactionRequest
	(*BatchFraudResponse)(nil),      // 5: fraud_detection.BatchFraudResponse
	(*FraudAlertRequest)(nil),       // 6: fraud_detection.FraudAlertRequest
	(*ModelInfoRequest)(nil),        // 7: fraud_detection.ModelInfoRequest
	(*ModelInfo)(nil),               // 8: fraud_detection.ModelInfo
	(*ModelUpdateRequest)(nil),      // 9: fraud_detection.ModelUpdateRequest
	(*ModelUpdateResponse)(nil),     // 10: fraud_detection.ModelUpdateResponse
	(*MetricsRequest)(nil),          // 11: fraud_detection.MetricsRequest
	(*ModelMetrics)(nil),            // 12: fraud_detection.ModelMetrics
	nil,                             // 13: fraud_detection.TransactionRequest.AdditionalFeaturesEntry
	nil,                             // 14: fraud_detection.ModelUpdateRequest.MetadataEntry
}
var file_protos_fraud_detection_proto_depIdxs = []int32{
	13, // 0: fraud_detection.TransactionRequest.additional_features:type_name -> fraud_detection.TransactionRequest.AdditionalFeaturesEntry
	0,  // 1: fraud_detection.BatchTransactionRequest.transactions:type_name -> fraud_detection.TransactionRequest
	1,  // 2: fraud_detection.BatchFraudResponse.responses:type_name -> fraud_detection.FraudResponse
	14, // 3: fraud_detection.ModelUpdateRequest.metadata:type_name -> fraud_detection.ModelUpdateRequest.MetadataEntry
	0,  // 4: fraud_detection.FraudDetectionService.ProcessTransaction:input_type -> fraud_detection.TransactionRequest
	0,  // 5: fraud_detection.FraudDetectionService.GetFraudScore:input_type -> fraud_detection.TransactionRequest
	6,  // 6: fraud_detection.FraudDetectionService.StreamFraudAlerts:input_type -> fraud_detection.FraudAlertRequest
	4,  // 7: fraud_detection.FraudDetectionService.BatchProcessTransactions:input_type -> fraud_detection.BatchTransactionRequest
	7,  // 8: fraud_detection.ModelService.GetModelInfo:input_type -> fraud_detection.ModelInfoRequest
	9,  // 9: fraud_detection.ModelService.UpdateModel:input_type -> fraud_detection.ModelUpdateRequest
	11, // 10: fraud_detection.ModelService.GetModelMetrics:input_type -> fraud_detection.MetricsRequest
	1,  // 11: fraud_detection.FraudDetectionService.ProcessTransaction:output_type -> fraud_detection.FraudResponse
	2,  // 12: fraud_detection.FraudDetectionService.GetFraudScore:output_type -> fraud_detection.FraudScoreResponse
	3,  // 13: fraud_detection.FraudDetectionService.StreamFraudAlerts:output_type -> fraud_detection.FraudAlert
	5,  // 14: fraud_detection.FraudDetectionService.BatchProcessTransactions:output_type -> fraud_detection.BatchFraudResponse
	8,  // 15: fraud_detection.ModelService.GetModelInfo:output_type -> fraud_detection.ModelInfo
	10, // 16: fraud_detection.ModelService.UpdateModel:output_type -> fraud_detection.ModelUpdateResponse
	12, // 17: fraud_detection.ModelService.GetModelMetrics:output_type -> fraud_detection.ModelMetrics
	11, // [11:18] is the sub-list for method output_type
	4,  // [4:11] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_protos_fraud_detection_proto_init() }
func file_protos_fraud_detection_proto_init() {
	if File_protos_fraud_detection_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_fraud_detection_proto_rawDesc), len(file_protos_fraud_detection_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_protos_fraud_detection_proto_goTypes,
		DependencyIndexes: file_protos_fraud_detection_proto_depIdxs,
		MessageInfos:      file_protos_fraud_detection_proto_msgTypes,
	}.Build()
	File_protos_fraud_detection_proto = out.File
	file_protos_fraud_detection_proto_goTypes = nil
	file_protos_fraud_detection_proto_depIdxs = nil
}
